---
# tasks file for httpd
- name: Installing httpd
  yum: 
    name: httpd
    state: latest
  notify: restart httpd
- name: Copying Files
  copy: 
    src: index.html
    dest: "{{ dest }}/index.html"
    mode: 0766
  notify: restart httpd 
     
